- name: Add PostgreSQL {{ pg_version }} repo
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Disable built-in PostgreSQL module
  command: dnf -qy module disable postgresql
  changed_when: false

- name: Install PostgreSQL {{ pg_version }} and Patroni
  dnf:
    name:
      - postgresql{{ pg_version }}
      - postgresql{{ pg_version }}-server
      - python3-pip
    state: present

- name: Install Patroni via pip
  pip:
    name: patroni
    executable: pip3

- name: Initialize PostgreSQL cluster
  command: /usr/pgsql-{{ pg_version }}/bin/postgresql-{{ pg_version }}-setup initdb
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"

- name: Deploy Patroni config
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    owner: root
    group: root
    mode: '0644'

- name: Create systemd unit for Patroni
  copy:
    dest: /etc/systemd/system/patroni.service
    content: |
      [Unit]
      Description=Patroni PostgreSQL HA
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/patroni /etc/patroni.yml
      Restart=always
      User=postgres

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Patroni
  systemd:
    name: patroni
    enabled: true
    state: started
    daemon_reload: true

- name: Install Keepalived
  dnf:
    name: keepalived
    state: present

- name: Deploy Keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Keepalived
  systemd:
    name: keepalived
    enabled: true
    state: started