---
- name: Installer le dépôt PostgreSQL 16
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Désactiver le module PostgreSQL par défaut
  command: dnf -qy module disable postgresql

- name: Installer PostgreSQL 16
  dnf:
    name:
      - postgresql16
      - postgresql16-server
    state: present

- name: Installer pip3 si absent
  package:
    name: python3-pip
    state: present
- name: Installer psycopg2-binary requis par Patroni
  pip:
    name: psycopg2-binary
    executable: pip3    

- name: Installer Patroni avec etcd
  pip:
    name: patroni[etcd]
    executable: pip3

- name: Installer Keepalived
  dnf:
    name: keepalived
    state: present

- name: Créer le répertoire de données PostgreSQL
  file:
    path: "{{ patroni_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Créer le dossier /etc/keepalived
  file:
    path: /etc/keepalived
    state: directory
    mode: '0755'

- name: Déployer la configuration Patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    mode: '0644'
  notify: restart patroni

- name: Déployer la configuration Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: restart keepalived

- name: Créer le script de surveillance Patroni pour Keepalived
  copy:
    dest: /usr/local/bin/check_patroni.sh
    mode: '0755'
    content: |
      #!/bin/bash
      curl -sf http://localhost:8008 | grep '"role": "leader"' > /dev/null
      exit $?

- name: Créer le service systemd pour Patroni
  copy:
    dest: /etc/systemd/system/patroni.service
    content: |
      [Unit]
      Description=Patroni PostgreSQL HA
      After=network.target

      [Service]
      Type=simple
      User=postgres
      ExecStart=/usr/local/bin/patroni /etc/patroni.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Recharger systemd
  command: systemctl daemon-reload

- name: Activer et démarrer Patroni & Keepalived
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - patroni
    - keepalived