---
- name: Ajouter le repo PostgreSQL {{ pg_version }}
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Désactiver le module PostgreSQL natif
  dnf:
    name: '@postgresql'
    state: absent
  ignore_errors: yes

- name: Installer PostgreSQL, pip et dépendances
  dnf:
    name:
      - postgresql{{ pg_version }}
      - postgresql{{ pg_version }}-server
      - python3-pip
    state: present

- name: Initialiser la base de données
  command: "{{ pg_bin_dir }}/postgresql-{{ pg_version }}-setup initdb"
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"

- name: Installer Patroni via pip
  pip:
    name: "patroni{{ patroni_version }}"
    executable: pip3
    state: present

- name: Déployer la configuration Patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Déployer l’unité systemd Patroni
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Patroni

- name: Activer et démarrer Patroni
  systemd:
    name: patroni
    enabled: yes
    state: started
    daemon_reload: no