- name: Install PostgreSQL 18 & Patroni
  ansible.builtin.yum:
    name:
      - postgresql-prereq
      - postgresql{{ pg_version }}-socle
      - postgresql-socle
      - patroni
      - patroni-etcd
      - keepalived
    state: present

- name: Create PG data & archive dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"
  loop:
    - "{{ data_dir }}"
    - "{{ archive_dir }}"
    - "{{ wal_dir }}"

- name: Set SELinux contexts on PG directories
  ansible_posix.seboolean:
    name: virtusenfs
    state: yes
    persistent: yes

- name: Apply postgresql-selinux-patroni rpm
  ansible.builtin.yum:
    name: postgresql-selinux-patroni
    state: present

- name: Allow Etcd ports in SELinux
  ansible.builtin.command: semanage port -a -t httpportt -p tcp 2379
  args:
    warn: false

- name: Generate patroni.yml
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: 0644

- name: Disable native PG service
  ansible.builtin.systemd:
    name: "pgsql_{{ instance }}.service"
    enabled: no
    state: stopped

- name: Enable & start Patroni
  ansible.builtin.systemd:
    name: patroni
    enabled: yes
    state: restarted