- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: no
    state: stopped

- name: Ensure chrony is installed & running
  ansible.builtin.yum:
    name: chrony
    state: present

- name: Configure NTP servers
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: Start chronyd
  ansible.builtin.service:
    name: chronyd
    enabled: yes
    state: started

- name: Create sinaps user
  ansible.builtin.user:
    name: sinaps
    shell: /sbin/nologin

- name: Install prerequisites
  ansible.builtin.yum:
    name:
      - epel-release
      - curl
    state: present