- name: Install Etcd
  ansible.builtin.yum:
    name: etcd
    state: present

- name: Configure /etc/etcd/etcd.conf
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: 0644

- name: Enable and start etcd
  ansible.builtin.systemd:
    name: etcd
    enabled: yes
    state: started