---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Patroni
  systemd:
    name: patroni
    state: restarted
    
- name: Restart keepalived
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: yes    