- name: Setup cluster HA PostgreSQL 18
  hosts: all
  become: true
  vars:
    pg_version: "18"
    instance: "ha_pg18"
    data_dir: "/var/lib/pgsql/{{ instance }}/data"
    archive_dir: "/var/lib/pgsql/{{ instance }}/archives"
    wal_dir: "/var/lib/pgsql/{{ instance }}/wal"
    etcdcluster: "{{ groups['etcd'] | map('extract', hostvars, ['ansiblehost']) | join(':2379,') }}:2379"
    patronicluster: "{{ groups['etcd'] | map('extract', hostvars, ['ansiblehost']) }}"
  roles:
    - common
    - etcd
    - patroni
    - keepalived
    - watchdog