- name: Install Keepalived
  ansible.builtin.yum:
    name: keepalived
    state: present

- name: Deploy keepalived.conf
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644

- name: Enable & start Keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    state: started